"""
evaluate_clinical_concepts.py
=======================================================================
Table 2 of the paper: how well does the offline clinical-concept
generation represent the clinical information in the original complaint?
=======================================================================

Mirrors latex/article.tex (tab:concept_similarity):

  * 10 independently selected random samples of 100 chief complaints
    (a total of 1,000 complaint-concept comparisons);
  * for each complaint an English clinical concept is generated by the
    offline, CPU-only pipeline (fuzzy Roman Urdu mapping -> Qwen2.5 via
    the local Ollama service, temperature 0.0, with few-shot examples);
  * the generated concept is compared word-level against the REFERENCE
    clinical concept, treating clinically equivalent terms as matches;
  * per complaint:
        P = N_match / N_gen        (N_gen = words generated)
        R = N_match / N_ref        (N_ref = words in the reference)
        F1 = 2 P R / (P + R)
    and per run the mean P, mean R and mean F1 over the 100 complaints.

REFERENCE CONCEPT SOURCE
------------------------
The pool is cardiac_english_2252.csv: the 2,252 synthetic cardiac
complaints that carry a gold English reference. That gold English is the
reference clinical concept this script compares the generated concept
against. It is the only per-complaint clinical ground truth this
repository ships; if the paper's reference concepts differ, pass the
file via --pool and they will be used instead.

Assumptions recorded here because they change the numbers:
  * token match is a bag overlap: a word tout of the shorter side can
    match at most min(count_gen, count_ref) times.
  * stop words are removed with the serving bundle's learned list, so
    function words cannot inflate agreement.
  * SEMANTIC_EQUIV below is the equivalence table. It uses exactly the
    pair cited by the paper (tachycardia<->palpitations,
    vertigo<->dizziness) plus a small set of unambiguous clinical
    synonyms. Add to this list if the paper used a richer table.

CHECKPOINTING
-------------
Every complaint row is appended to <out>_complaints.csv as soon as it is
scored. If the run is interrupted, re-run with the same --out and
--seed-offset; finished complaint rows are skipped and the run resumes.
Run summaries accumulate in <out>_runs.csv.

USAGE
-----
    python evaluate_clinical_concepts.py                 # 10 x 100, qwen2.5
    python evaluate_clinical_concepts.py --runs 3               # 3 runs only
    python evaluate_clinical_concepts.py --n 100               # default
    python evaluate_clinical_concepts.py --model llama3.2:latest
    python evaluate_clinical_concepts.py --max-complaints 2 --runs 1   # smoke
=======================================================================
"""

import argparse
import csv
import json
import os
import random
import sys
import time

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

import pandas as pd

from src.offline_pipeline import (
    OLLAMA_MODEL, OLLAMA_URL, RETRY_NUDGE, USER_TEMPLATE,
    _ollama_chat, _strip_labels, fuzzy_normalize_roman_urdu,
    has_medical_signal, is_non_latin_script, sanitize_translation,
    select_translation_model,
)

DEFAULT_POOL = "cardiac_english_2252.csv"
DEFAULT_RUNS = 10
DEFAULT_N = 100
DEFAULT_SEED_OFFSET = 20260920
CONCEPT_TIMEOUT = 300.0

#: Tokens removed from BOTH the generated concept and the reference
#: before matching (the paper's "stop-word removal"). This is NOT the
#: serving bundle's learned list, which was trained for the classifier
#: and would strip clinical words like "chest"/"shortness". This is an
#: explicit English function-word set plus emergency-note filler
#: ("patient presents with ... since 3 days"), kept here so a reviewer
#: can audit exactly what is filtered. The same list applies to both
#: sides, so it cannot favour one direction.
STOPWORDS = set("""
a an the this that these those some any no every all both each other
another such i me my mine we us our ours you your yours he him his she
her hers it its they them their theirs who whom whose which what
about above across after among around at before behind below beneath
beside between beyond by despite down during except for from in inside
into near of off on onto out outside over past since through throughout
to toward towards under underneath until up upon with within without
and but or nor so yet because although though unless while whereas as
if is are was were be been being am do does did done have has had
having will would shall should may might can could must ought
also very quite rather fairly just still already only then there here
now yesterday today always often sometimes never again further about
almost enough even ever too when where why how more most much many
one two three four five six seven eight nine ten eleven twelve thirteen
fourteen fifteen twenty thirty forty fifty sixty seventy eighty ninety
hundred thousand
patient patients patient's pt pts presents presented presenting
complain complains complained of reports reported says said told
history hx with since days day week weeks month months year years old
age times episode episodes duration ago prior previous onwards came
camein brought admitted evaluated seen went get got having begins
""".split())

#: Clinical concepts that score as semantic matches although the surface
#: words differ. Kept deliberately small: every pair here is an
#: unambiguous clinical synonym. Adding pairs inflates agreement, so this
#: list is the number a reviewer can audit.
SEMANTIC_EQUIV = {
    "tachycardia": "palpitations",
    "palpitation":  "palpitations",
    "vertigo":      "dizziness",
    "giddiness":    "dizziness",
    "diaphoresis":  "sweating",
    "perspiration": "sweating",
    "pyrexia":      "fever",
}

#: Two concept-form demonstrations for the few-shot turns. Deliberately
#: chosen complaints that are NOT in the 2,252-row pool, so the model
#: cannot echo an answer it has simply seen before.
CONCEPT_FEWSHOT = [
    ("gala kharab hai aur khansi aa rahi hai", "sore throat cough"),
    ("beti ko tez bukhar hai aur kaanp rahi hai", "fever rigors"),
]

SYSTEM_PROMPT = """### 0. OPERATING CONTEXT - READ FIRST
You are a precise clinical documentation component in an offline medical
triage system. You convert a Roman Urdu emergency complaint into a compact
English CLINICAL CONCEPT.

### 1. TASK
Render the complaint as a short sequence of space-separated clinical concepts
(noun phrases only), NOT a grammatical sentence. Keep every symptom, sign
and body part that is PRESENT in the complaint. Do NOT add a symptom or body
part that is absent. Do NOT include the age, vitals, or any conversational
filler.

### 2. FORMAT
Output ONLY the concept words. No preamble, no quoting, no label, no
explanation, no disclaimers of any kind.

### 3. EXAMPLES
Record: <record>seena mein dard hua aur pasina aa raha hai</record>
Concept: chest pain sweating

Record: <record>dil ki dhadkan tez ho rahi hai</record>
Concept: palpitations"""


# ----------------------------------------------------------------------
# concept generation
# ----------------------------------------------------------------------

def generate_concept(text, model, url=OLLAMA_URL, timeout=CONCEPT_TIMEOUT,
                     attempts_transport=2):
    """Return (concept, model_used) or (None, model_used) on failure.

    Original Roman Urdu -> fuzzy dictionary -> Qwen2.5 (temperature 0.0),
    following the same guardrails and retry shape as translate_roman_urdu().
    """
    text = (text or "").strip()
    if not text:
        return None, model

    text = fuzzy_normalize_roman_urdu(text)
    if is_non_latin_script(text):
        return None, model
    if not has_medical_signal(text):
        return None, model

    resolved = select_translation_model(preferred=model)
    if resolved is None:
        print(f"[concept] no model installed - run 'ollama pull qwen2.5'",
              flush=True)
        return None, model
    model = resolved

    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    for src, want in CONCEPT_FEWSHOT:
        messages.append({"role": "user", "content": USER_TEMPLATE.format(src)})
        messages.append({"role": "assistant", "content": want})
    messages.append({"role": "user", "content": USER_TEMPLATE.format(text)})

    for attempt in (1, 2):
        raw = None
        for _ in range(attempts_transport):
            raw = _ollama_chat(messages, model, url, timeout)
            if raw is not None:
                break
            time.sleep(2.0)
        if raw is None:
            return None, model
        cleaned = _strip_labels(raw)
        out = sanitize_translation(cleaned, text)
        if out is not None:
            return out, model
        messages.append({"role": "assistant", "content": raw})
        messages.append({"role": "user", "content": RETRY_NUDGE})
    print(f"[concept] {model} refused twice - complaint left unscored.",
          flush=True)
    return None, model


# ----------------------------------------------------------------------
# token-level matching
# ----------------------------------------------------------------------

def tokens_of(text):
    toks = []
    for w in str(text).lower().split():
        w = w.strip(".,;:!?\"'()[]{}<>-")
        if not w or w in STOPWORDS:
            continue
        w = SEMANTIC_EQUIV.get(w, w)
        toks.append(w)
    return toks


def score_concept(concept, reference):
    """Return (n_gen, n_ref, n_match, P, R, F1)."""
    gen = tokens_of(concept)
    ref = tokens_of(reference)
    n_gen, n_ref = len(gen), len(ref)
    if n_gen and n_ref:
        from collections import Counter
        cg, cr = Counter(gen), Counter(ref)
        n_match = sum(min(cg[w], cr[w]) for w in set(cg) & set(cr))
    else:
        n_match = 0
    if n_gen and n_match:
        p = n_match / n_gen
    else:
        p = 0.0
    if n_ref and n_match:
        r = n_match / n_ref
    else:
        r = 0.0
    f1 = 0.0 if (p + r) == 0 else 2 * p * r / (p + r)
    return n_gen, n_ref, n_match, p, r, f1


# ----------------------------------------------------------------------
# checkpointed evaluation
# ----------------------------------------------------------------------

def done_keys(complaints_csv):
    """Return {(run, complaint): True} already scored."""
    done = set()
    if not os.path.exists(complaints_csv):
        return done
    with open(complaints_csv, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            done.add((int(row["run"]), row["complaint"]))
    return done


COMPLAINT_COLS = [
    "run", "seed", "complaint", "reference", "concept", "model",
    "n_gen", "n_ref", "n_match", "P", "R", "F1", "ts",
]


def main():
    ap = argparse.ArgumentParser(description="Clinical-concept evaluation (paper Table 2).")
    ap.add_argument("--pool", default=DEFAULT_POOL)
    ap.add_argument("--runs", type=int, default=DEFAULT_RUNS)
    ap.add_argument("--n", type=int, default=DEFAULT_N)
    ap.add_argument("--seed-offset", type=int, default=DEFAULT_SEED_OFFSET)
    ap.add_argument("--model", default=OLLAMA_MODEL)
    ap.add_argument("--out", default="clinical_concept_evaluation")
    ap.add_argument("--max-complaints", type=int, default=0,
                    help="stop after this many scored complaints (smoke test)")
    args = ap.parse_args()

    pool_path = args.pool if os.path.isabs(args.pool) else os.path.join(_HERE, args.pool)
    pool = pd.read_csv(pool_path)
    if not {"Complaint_Text", "English_Translation"}.issubset(pool.columns):
        raise SystemExit(f"{args.pool} must have Complaint_Text and "
                         f"English_Translation columns")
    pool = pool.dropna(subset=["English_Translation"]).reset_index(drop=True)
    if len(pool) < args.n:
        raise SystemExit(f"pool has {len(pool)} rows; need >= {args.n}")
    print(f"[ok] pool: {args.pool} ({len(pool)} rows with a gold English)")
    print(f"[ok] {args.runs} runs x {args.n} complaints = "
          f"{args.runs * args.n} comparisons, model={args.model}")

    complaints_csv = args.out + "_complaints.csv"
    runs_csv = args.out + "_runs.csv"
    done = done_keys(complaints_csv)
    print(f"[ok] checkpointed rows present: {len(done)} (resumed where left)")

    scored = 0
    for run in range(1, args.runs + 1):
        seed = args.seed_offset + run
        rng = random.Random(seed)
        sample = pool.sample(n=args.n, random_state=seed).reset_index(drop=True)
        ps, rs, f1s, fails = [], [], [], 0
        for i, row in sample.iterrows():
            complaint = str(row["Complaint_Text"])
            if (run, complaint) in done:
                continue
            ref = str(row["English_Translation"])
            concept, used = generate_concept(complaint, model=args.model)
            if not concept:
                fails += 1
            n_gen, n_ref, n_match, p, r, f1 = score_concept(
                concept or "", ref)
            ps.append(p); rs.append(r); f1s.append(f1)
            new_file = not os.path.exists(complaints_csv)
            with open(complaints_csv, "a", newline="", encoding="utf-8") as f:
                w = csv.writer(f)
                if new_file:
                    w.writerow(COMPLAINT_COLS)
                w.writerow([
                    run, seed, complaint, ref, concept or "", used,
                    n_gen, n_ref, n_match, round(p, 4), round(r, 4),
                    round(f1, 4), time.strftime("%Y-%m-%d %H:%M:%S"),
                ])
            scored += 1
            if scored % 25 == 0 or concept is None:
                print(f"  [run {run}] {i + 1}/{len(sample)} scored, "
                      f"cumulative={scored}", flush=True)
            if args.max_complaints and scored >= args.max_complaints:
                print(f"[stop] reached --max-complaints {args.max_complaints}")
                return
        if ps:
            mp, mr, mf = sum(ps) / len(ps), sum(rs) / len(rs), sum(f1s) / len(f1s)
            with open(runs_csv, "a", newline="", encoding="utf-8") as f:
                csv.writer(f).writerow([run, args.n, round(mp, 4),
                                        round(mr, 4), round(mf, 4), fails])
            print(f"[run {run}] P={mp:.4f}  R={mr:.4f}  F1={mf:.4f}  "
                  f"(concept failures: {fails})", flush=True)

    # ---- aggregate across completed runs ----
    if os.path.exists(runs_csv):
        df = pd.read_csv(runs_csv, header=None,
                         names=["run", "n", "P", "R", "F1", "failures"])
        print("\n" + "=" * 70)
        print("TABLE 2  -  CLINICAL CONCEPT EVALUATION")
        print("=" * 70)
        print(f"{'SN':>3} {'#':>4} {'Precision':>10} {'Recall':>9} {'Mean F1':>9}")
        for _, r in df.iterrows():
            print(f"{int(r['run']):>3} {int(r['n']):>4} "
                  f"{r['P']:>10.4f} {r['R']:>9.4f} {r['F1']:>9.4f}")
        me = lambda x: (x.mean(), x.std(ddof=0))
        mp, sp = me(df.P); mr, sr = me(df.R); mf, sf = me(df.F1)
        print("-" * 70)
        print(f"Mean +/- SD (N={len(df)} runs): "
              f"P {mp:.4f} +/- {sp:.4f} | R {mr:.4f} +/- {sr:.4f} | "
              f"F1 {mf:.4f} +/- {sf:.4f}")
        print("\nLaTeX rows to paste into tab:concept_similarity:\n")
        for _, r in df.iterrows():
            print(f"{int(r['run'])}  & 100 & {r['P']:.4f} & {r['R']:.4f} "
                  f"& {r['F1']:.4f} \\\\")
        print(f"\\hline")
        print(f"\\textbf{{Mean $\\pm$ SD}} & \\textbf{{{len(df)*args.n}}} & "
              f"\\textbf{{{mp:.4f} $\\pm$ {sp:.4f}}} & "
              f"\\textbf{{{mr:.4f} $\\pm$ {sr:.4f}}} & "
              f"\\textbf{{{mf:.4f} $\\pm$ {sf:.4f}}} \\\\")


if __name__ == "__main__":
    main()